### ISSUE TITLE
basic build fails (source/client/index.js)

### ISSUE THREAD

**Issue by tashburn** [cloverfield-tools/universal-react-boilerplate#114]
downloaded the code, ran `npm install` and then `npm run build:dev`, and get this error -

ERROR in ./source/client/index.js
Module build failed: SyntaxError: /Users/trent/home/projects/know.how/code2/source/client/index.js: Unexpected token (15:4)
  13 | const store = createStore(
  14 |   combineReducers({
> 15 |     ...reducers,
     |     ^
  16 |     routing: routerReducer
  17 |   }),
  18 |   // hydrating server.
    at Parser.pp$5.raise (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:4333:13)
    at Parser.pp.unexpected (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:1705:8)
    at Parser.pp$3.parseIdentifier (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:4211:10)
    at Parser.pp$3.parsePropertyName (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:4031:96)
    at Parser.pp$3.parseObj (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3947:12)
    at Parser.pp$3.parseExprAtom (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3639:19)
    at Parser.pp$3.parseExprSubscripts (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3414:19)
    at Parser.pp$3.parseMaybeUnary (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3394:19)
    at Parser.pp$3.parseExprOps (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3324:19)
    at Parser.pp$3.parseMaybeConditional (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3301:19)
    at Parser.pp$3.parseMaybeAssign (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3264:19)
    at Parser.pp$3.parseExprListItem (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:4190:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3493:20)
    at Parser.pp$3.parseSubscripts (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3453:31)
    at Parser.pp$3.parseExprSubscripts (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3424:15)
    at Parser.pp$3.parseMaybeUnary (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3394:19)
    at Parser.pp$3.parseExprOps (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3324:19)
    at Parser.pp$3.parseMaybeConditional (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3301:19)
    at Parser.pp$3.parseMaybeAssign (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3264:19)
    at Parser.pp$3.parseExprListItem (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:4190:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3493:20)
    at Parser.pp$3.parseSubscripts (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3453:31)
    at Parser.pp$3.parseExprSubscripts (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3424:15)
    at Parser.pp$3.parseMaybeUnary (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3394:19)
    at Parser.pp$3.parseExprOps (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3324:19)
    at Parser.pp$3.parseMaybeConditional (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3301:19)
    at Parser.pp$3.parseMaybeAssign (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:3264:19)
    at Parser.pp$1.parseVar (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:2284:24)
    at Parser.pp$1.parseVarStatement (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:2115:8)
    at Parser.pp$1.parseStatement (/Users/trent/home/projects/know.how/code2/node_modules/babylon/lib/index.js:1807:19)
 @ multi main

**Comment by ericelliott** [comment]
Try using Next.js instead of this boilerplate. =)
